version: '3'
services:
  homeassistant:
    container_name: homeassistant
    build: .
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8123:8123
      - 8008-8009:8008-8009
      - 5353:5353
      - 8443:8443
    depends_on: 
      - mochad

  mochad:
    container_name: mochad
    build: ./mochad
    restart: unless-stopped
    command: ./mochad -d
    devices:
      - /dev/bus/usb

  hass-config:
    container_name: config
    image: "causticlab/hass-configurator-docker:latest"
    restart: unless-stopped
    ports:
      - "8124:3218/tcp"
    volumes:
      - "./config:/app/config"
